# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.matan_service_pb2 as matan__service__pb2


class MatanServiceStub(object):
    """---------- Matan's Service ----------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/matanservice.MatanService/SayHello',
                request_serializer=matan__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=matan__service__pb2.HelloReply.FromString,
                )
        self.SayHi = channel.unary_unary(
                '/matanservice.MatanService/SayHi',
                request_serializer=matan__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=matan__service__pb2.HelloReply.FromString,
                )


class MatanServiceServicer(object):
    """---------- Matan's Service ----------
    """

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=matan__service__pb2.HelloRequest.FromString,
                    response_serializer=matan__service__pb2.HelloReply.SerializeToString,
            ),
            'SayHi': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHi,
                    request_deserializer=matan__service__pb2.HelloRequest.FromString,
                    response_serializer=matan__service__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matanservice.MatanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MatanService(object):
    """---------- Matan's Service ----------
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/matanservice.MatanService/SayHello',
            matan__service__pb2.HelloRequest.SerializeToString,
            matan__service__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/matanservice.MatanService/SayHi',
            matan__service__pb2.HelloRequest.SerializeToString,
            matan__service__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
